CREATE TABLE tbl_customer (
    CustomerId INT IDENTITY(1,1) PRIMARY KEY Not Null,
    CustomerCode NVARCHAR(50)Not Null,
    LedgerCategory int Not Null,
    FirmType int Not Null,
    Website NVARCHAR(200)Not Null,
    PrimaryMobileNo NVARCHAR(20)Not Null,
    SalesRep NVARCHAR(100)Not Null,
    CreditDays int Not Null,
    CreditLimit DECIMAL(18,2) Not Null,
    GodownName NVARCHAR(100) Not Null,
    Address1 NVARCHAR(200) Not Null,
    Address2 NVARCHAR(200) Not Null,
    Area NVARCHAR(100) Not Null,
    City NVARCHAR(100) Not Null,
    State NVARCHAR(100) Not Null,
    Pincode NVARCHAR(20) Not Null,
    LicenseNo NVARCHAR(50) Not Null,
    PANNo NVARCHAR(20) Not Null,
    GSTINNo NVARCHAR(20) Not Null,
    Email NVARCHAR(150) Not Null,
    PriceLevel NVARCHAR(100) Not Null,
    ContactPerson NVARCHAR(100) Not Null,
    ContactNo NVARCHAR(20) Not Null,
    IsActive BIT Not Null,
	CreatedAT DATETIME DEFAULT GETDATE(),
	UpdateAT DATETIME NULL
);