CREATE TABLE tbl_godown (
    GodownID INT IDENTITY(1,1) PRIMARY KEY Not null,
    LocationID INT NOT NULL,   
    GodownName NVARCHAR(100) NOT NULL,
    Address1 NVARCHAR(200) NOT NULL,
    Address2 NVARCHAR(200) NOT NULL,
    PhoneNo NVARCHAR(20) NOT NULL,
    AltPhoneNo NVARCHAR(20) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
	CreatedAT DATETIME DEFAULT GETDATE(),
	UpdateAT DATETIME NULL
);