CREATE TABLE tbl_role (
    RoleID INT IDENTITY(1,1) PRIMARY KEY Not Null,
    RoleName NVARCHAR(100) NOT NULL,
    RoleType NVARCHAR(50) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAT DATETIME DEFAULT GETDATE(),
	UpdateAT DATETIME NULL
);